name: 'Huidetang'
root: '.'
cache_path: '.licenses'
apps:
  - source_path: './backend'
  - source_path: './frontend'
sources:
  yarn: true
  pipenv: true
yarn:
  production_only: false
allowed:
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - mit
  - cc0-1.0
  - unlicense
  - 0bsd
  - wtfpl
  - mpl-2.0