version: '3.7'
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app/:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:password@postgres:5432/postgres'
      AWS_S3_CUSTOM_DOMAIN: 'minio:9000'
      AWS_STORAGE_BUCKET_NAME: 'static'
      AWS_ACCESS_KEY_ID: 'minioadmin'
      AWS_SECRET_ACCESS_KEY: 'minioadmin'
      AWS_S3_URL_PROTOCOL: 'http:'
    depends_on:
      - "postgres"
      - "minio"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development
  minio:
    image: minio/minio:latest
    container_name: 'minio'
    ports:
      - 9090:9000
    volumes:
      - ./minio/data:/data
      - ./minio/export:/export
      - ./minio/config:/root/.minio
      - ./minio/policies:/policies
    environment:
      MINIO_ACCESS_KEY: 'development'
      MINIO_SECRET_KEY: 'p@ssword'
    entrypoint:
      - /bin/sh
      - -c
    command:
      - "mkdir -p /data/.minio.sys/buckets; cp -r /policies/* /data/.minio.sys/; cp -r /export/* /data/; /usr/bin/minio server /data"
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add static http://minio:9000 development p@ssword) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb static/images;
      /usr/bin/mc admin user add static wagtail;
      /usr/bin/mc policy download static/images;
      exit 0;
      "
volumes:
  db-data: